Fix beforeMarshall if file uploads are array
FriendsOfCake/cakephp-upload pull request #588
Opened 2022-09-06 09:29 UTC by albertcansado

Fix error "Call to a member function getError() on array" when uploaded file is an array.

2022-09-06 10:39 UTC, davidyell commented
A few small bits to tidy up.

2022-10-03 14:14 UTC, TerryKern requested changes

2022-10-03 14:14 UTC, TerryKern commented on tests/TestCase/Model/Behavior/UploadBehaviorTest.php
> +    }
>  Parse error: syntax error, unexpected '$file' (T_VARIABLE), expecting ',' or ')' in /home/runner/work/cakephp-upload/cakephp-upload/tests/TestCase/Model/Behavior/UploadBehaviorTest.php on line 805

To fix the above error: 

```suggestion
        return array_map(
            function (UploadedFileInterface $file) {
                return [
                    'tmp_name' => '',
                    'error' => $file->getError(),
                    'name' => $file->getClientFilename(),
                    'type' => $file->getClientMediaType(),
                    'size' => $file->getSize(),
                ];
            },
            $data
        );
    }
```

2022-10-03 14:39 UTC, ravage84 commented
@albertcansado the code needs to have PHP 7.2 compat as it needs to keep CakePHP 4.x before 4.4 compatibility.

https://github.com/FriendsOfCake/cakephp-upload/blob/878cba2420e055d821eebeb50659141e3523e22d/composer.json#L19

@TerryKern's changes take care of that.

2022-10-18 07:40 UTC, merged